config/routes.rb
Rails.application.routes.draw do
  root :to => 'questions#index'
  resources :questions do
    resources :answers
  end

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  validates :body, :presence => true, :uniqueness => true
  validates :question_id, :presence => true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  validates :heading, :presence => true, :uniqueness => true
  validates :post, :presence => true, :uniqueness => true

  scope :most_recent, -> {order(created_at: :desc).limit(4)}
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  before_save :encrypt_password
  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authorize, only: [:edit, :destroy]
    def new
      @question = Question.find(params[:question_id])
      @answer = @question.answers.new
    end

  def create
      @question = Question.find(params[:question_id])
      @answer = @question.answers.new(answer_params)
      if @answer.save
        redirect_to question_path(@answer.question)
      else
        render :new
      end
    end

    def edit
      @question = Question.find(params[:question_id])
      @answer = Answer.find(params[:id])
    end

    def update
     @question = Question.find(params[:question_id])
     @answer= Answer.find(params[:id])
     if @answer.update(answer_params)
       redirect_to answers_path(@answer.question)
     else
       render :edit
     end
   end

   def destroy
     @question = Question.find(params[:question_id])
     @answer = Answer.find(params[:id])
     @answer.destroy
     redirect_to question_path(@answer.question)
   end



  private
    def answer_params
      params.require(:answer).permit(:body, :question_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize
    if !current_user
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_to '/'
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
 before_action :authorize, only: [:new, :show]

  def index
    @questions = Question.all
    @question_most_recent = Question.most_recent
    render :index
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    render :show
  end

  def new
    @question = Question.new
    render :new
  end

  def create

    @question = Question.new(question_params)
    if @question.save
      flash[:notice] = "Question successfully added!"
      redirect_to  questions_path
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
    render :edit
  end

  def update
   @question= Question.find(params[:id])
   if @question.update(question_params)
     redirect_to questions_path
   else
     render :edit
   end

   def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end
end

private
  def question_params
    params.require(:question).permit(:heading, :post)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  
  def create
    @user = User.authenticate(params[:email, :username], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've successfully signed up!"
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing up."
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_form.html.erb
<%= render('layouts/errors', :object => @answer) %>

<%= form_for [@question, @answer] do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <p><%= f.submit %></p>
<% end %>

app/views/answers/new.html.erb
<h1>New answer for <%= @question.heading %></h1>
                  <p><%= @question.heading %></p>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChickTech</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <%= current_user.email %> | <%= link_to "Sign out", '/signout' %>
    <% else %>
      <%= link_to "Sign up", 'signup' %> | <%= link_to "Sign in", '/signin' %>
    <% end %>

    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= render "layouts/errors", :object => @question %>

<%= form_for @question do |f| %>
  <%= f.label :heading %>
  <%= f.text_field :heading %>
  <%= f.label :post %>
  <%= f.text_field :post %>
  <%= f.submit %>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render "form" %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<h3>Here are some recent questions:</h3>
<ul>
  <% @question_most_recent.each do |question| %>
  <li><%=link_to question.heading, question_path(question) %></li>
  <% end %>
</ul>

<h3>All questions:</h3>
<ul>
  <% @questions.each do |question| %>
    <li><%= link_to question.heading, question_path(question) %></li>
  <% end %>
</ul>

<hr>

<%= link_to "New Question", new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render "form" %>

app/views/questions/show.html.erb
<h1><%= @question.heading %></h1>
<p><%= @question.post %></p>

<% if @question.answers.any? %>
  <h4>Here are the answers for this question:</h4>

  <ul>
    <% @question.answers.each do |answer| %>
      <li>
        <%= answer.body %> |
        <%= link_to "Edit", edit_question_answer_path(@question, answer) %> |
        <%= link_to "Delete", question_answer_path(@question, answer),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no answers yet!</p>
<% end %>

<p><%= link_to "Add an answer", new_question_answer_path(@question) %></p>
<p><%= link_to "Edit", edit_question_path(@question) %></p>
<p><%= link_to "Delete", question_path(@question),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to questions", questions_path %></p>

app/views/users/new.html.erb
<h1> Sign up</h1>
<%= form_for @user do |f| %>
  <%= f.label "Email" %>
  <%= f.text_field :email %>
  <%= f.label "Username" %>
  <%= f.text_field :username %>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>